### PR TITLE
Add Linear and Exponential models

### PR DESCRIPTION
**Pull request by aakankshaduggal**
## Related Issues and Dependencies

#17 
This notebook adds Linear and Exponential models for timeseries data.

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

… Explain your changes.

### CODE REVIEW

**Review by Shreyanand — CHANGES_REQUESTED** [review]
Added minor comments, the explanations look good! For the models failing, small changes in order should work.

**Comment by aakankshaduggal** [comment]
@Shreyanand Thanks for the review. The issues with the old models are now resolved.

**Comment by aakankshaduggal** [comment]
@MichaelClifford and @Shreyanand I have added the updated notebook with suggested changes :+1:

**Review by Shreyanand — APPROVED** [review]
LGTM

**Pull request merged**
